### ISSUE TITLE
Broke Extra networks 

### ISSUE THREAD

**Issue by bropines** [Kahsolt/stable-diffusion-webui-sonar#10]
After installing as an extension, the View / Hide extra networks button stops working

**Comment by Kahsolt** [comment]
😳 This sounds crazy.... sonar should never touch anything in the main ui panel.
Try uninstalling it, see if that extra networks button will rework.

**Comment by Kahsolt** [comment]
And, is there anything complaining on your console?

**Comment by bropines** [comment]
> And, is there anything complaining on your console?

It was fixed, but for how long.

**Comment by bropines** [comment]
Let's close the question for now
