### ISSUE TITLE
What is the upscale option for when we have Hires fix?

### ISSUE THREAD

**Issue by gilroff** [Kahsolt/stable-diffusion-webui-sonar#11]
Im confused

**Comment by Kahsolt** [comment]
Well, in the old days before `hires.fix` is refactored to separate the two steps of super-resolution and img2img, so that you can run upscaling without **img2img** processing, sonar added the upscale options as #3 requests.
Now it's ok to ignore it...

**Comment by gilroff** [comment]
Thank you!
