### ISSUE TITLE
Hard written path

### ISSUE THREAD

**Issue by AlphaUki** [Kahsolt/stable-diffusion-webui-sonar#13]
Line 32 of the script sonar.py, the directory name "stable-diffusion-webui-sonar" should not be hard written.
\_\_file\_\_ might be used, to allow changing the ext directory name.

**Comment by Kahsolt** [comment]
I wished so, but sd-webui executes scripts through the dynamic `eval()`, under this case `__file__` is not available from runtime, thus just left it hard-coded...
If you find any capable way, please feel free to tell me or make a PR :)
