### ISSUE TITLE
How does the code work exactly?

### ISSUE THREAD

**Issue by alexblattner** [Kahsolt/stable-diffusion-webui-sonar#23]
Hi, I need to replicate this for diffusers but I don't understand exactly what it is the code does. Could you explain more specifically? What is momentum on latent difference? What do you do with it exactly? How does the code try things with the same prompt and generate different results? Are you just switching seeds or something else?

I would appreciate an answer and thank you in advance for your time

**Comment by Kahsolt** [comment]
Though I've sent the reply directly through the email yesterday, I think I should paste it here to track a thread.

> Hi~ 
> This Momentum mechanism in sonar is a second–order like stuff, contrasting with first–order samplers like PLMS; nothing to do with the seed. You can roughly think of mixing up several latents to get a corrected latent, but this mixing is not in a weighted-sum manner like PLMS, but keep a momentum cache (same tensor size as latent image) that records the delta of the denoiser taken in the sampling steps, then sonar can **mix this delta** into later sampling step latents. 
> Now is bed time and I could explain more detailed tomorrow :)

**Comment by alexblattner** [comment]
I have finished implementing it for diffusers thanks to @Kahsolt 's help.

for anyone interested: https://github.com/alexblattner/modified-euler-samplers-for-sonar-diffusers
