### ISSUE TITLE
Getting an error when trying to use the script

### ISSUE THREAD

**Issue by adalast** [Kahsolt/stable-diffusion-webui-sonar#24]
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 's_min_uncond'

I have a negative prompt, so I'm not sure why this error is popping up.  It is specific to this extension as when I deactivate the script it goes away.

**Comment by Kahsolt** [comment]
You seem to use a very old sd-webui version, try update it~
If I'm not getting wrong `s_min_uncond` is introduced to sd-webui core since the official release `v1.1`
