### ISSUE TITLE
Getting an error when using the script

### ISSUE THREAD

**Issue by Kimiko-AI** [Kahsolt/stable-diffusion-webui-sonar#25]
` RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same`
![image](https://github.com/Kahsolt/stable-diffusion-webui-sonar/assets/105905988/fc2dfbc4-d7a2-4adc-89d2-63e43aa46462)
Here is my settings

**Comment by Kahsolt** [comment]
Other parts like LORA and various cross-attention speed up techincs may cause this.

try add command line arg `--no-half-vae` as a work around
[doc](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings)
