### ISSUE TITLE
any chance of adding a ComfyUI version?

### ISSUE THREAD

**Issue by blepping** [Kahsolt/stable-diffusion-webui-sonar#27]
hi! i love the Sonar Sampler, it's actually one thing i really miss after switching to ComfyUI. have you considered porting it? even just a really basic version that doesn't have the scaling or plot stuff would be very welcome.

**Comment by Kahsolt** [comment]
Yes, here is a port [https://github.com/alexblattner/modified-euler-samplers-for-sonar-diffusers](https://github.com/alexblattner/modified-euler-samplers-for-sonar-diffusers) made by @alexblattner 
I've checked the code months ago, the implementation should be OK, but no more updates since then..

**Comment by blepping** [comment]
thanks for the reply! that isn't a ComfyUI version (and i think ComfyUI uses a modified version of diffusers internally). what i am talking about would need to be written as a ComfyUI extension, but it seems like porting it from that code would be easier than the A1111 extension version. i might just be able to do it myself.

**Comment by Kahsolt** [comment]
Oh I remembered, that's a diffuser version :(
As for ComfyUI, it should be easy to start with a simple KSampler node, and follow what was done in the `modified-euler-samplers-for-sonar-diffusers` repo, have a try by yourself!
If you get somewhere confused, create a repo and let me PR :)

**Comment by blepping** [comment]
i really appreciate the offer and i am going to take you up on it!

this is what i have currently: https://github.com/blepping/ComfyUI-sonar/blob/main/py/sonar.py

i honestly don't know if it is even close to correct, i have no idea of what i am doing messing with the internals of samplers. all i can say is it produces pretty reasonable results when sampling, the results are different from the base Euler and Euler Ancestral samplers and changing stuff like the momentum weight does make the output change as well.

in addition to the repo you linked, i also used ComfyUI's built-in samplers as a reference: https://github.com/comfyanonymous/ComfyUI/blob/d0e2354c287d306b0559f1e570c79f2fdac064f4/comfy/k_diffusion/sampling.py#L126

if you have the time and are feeling very generous, could you please take a look and just see if what i did seems relatively sane? i don't have a good way to compare with the A1111 output unfortunately (and generally ComfyUI produces somewhat different results anyway)

**Comment by Kahsolt** [comment]
Wow, love your coding style, but where can I find that "SamplerCustom" node, as in your README shows, is it another extension?

updates: no bother I've found it, I'm starting to so some test :)

**Comment by blepping** [comment]
oh thank you! actually, i should probably have updated this issue, i got distracted. i've been using the samplers for a while and they actually work pretty well. i'll still be thrilled to receive any review/feedback though! i honestly have no idea what i'm doing modifying sampling routines, i think i got the DPM++ SDE one momentumized mostly by luck.

stuff like changing the initial noise type or sampling noise types can produce some really interesting results. (you might have already seen that in the example images.) can get some fun effects using _negative_ guidance also.

**Comment by Kahsolt** [comment]
Congratulations for your work! 🎉
yes I've seen your interesting ablation experiments on various noise distributions
gratefully you are also exploring things in the wild like me -- starting with an idea not theoretically right or even reasonable, but just wonder what will happen... the sonar's momentum is also not theoretically right (to approximate the annealing curve during training), it just to some degree works 🤣 
these trials would help understand how and why a neural model works in research, it's not targeted for production :)

**Comment by blepping** [comment]
> gratefully you are also exploring things in the wild like me -- starting with an idea not theoretically right or even reasonable, but just wonder what will happen

haha, yes, that's me in a nutshell. or if something produces pleasing/useful results then that's also good enough for me. the crazy green noise is nice for colorful stuff, like scenes with flowers.

i'm going to close this since it's _basically_ "solved". happy to receive any feedback or continue the conversation though! also if there's anything in my project you can use, please feel free — just keep in mind i didn't write any of the noise generation functions and actual sampling (except the minor modification to momentumize dpmpp_sde i guess) so i can't give permission for those (the license is probably fine though) and the original source should be credited not me.
