### ISSUE TITLE
Workflow for this?

### ISSUE THREAD

**Issue by Woisek** [Kahsolt/stable-diffusion-webui-sonar#3]
This looks interesting, but I don't understand how the workflow is executed.
Any words or tutorial on how to "search" for better variants?

Thanks in advance.

**Comment by Kahsolt** [comment]
just care about the `Momentum (current)` and `Momentum (history)` 😀

`current` is a enable-switch or `1 - momentum strength`:

- when value is large (→1.0), momentum mechanism tends not to work
- when value is small (→0.5), it over works to break images 🤣

`history` is the main slider to search for good things (in `pos` mode):

- the larger, take the momentum effects more
- the smaller, take the momentum effects less

so typically my workflow:

- set `history = 1`, which means maximizing the momentum effect
- search for a nice `current` from `1.0` down to `0.8`, stop at when you think your image is broken
- search for a nice `history` from `1.0` down to `0.0`

hope it helps :)

**Comment by Woisek** [comment]
Allright, this already helps a lot.
Further question:
When I import an image to the img2img, the settings of this image will be filled in. Using the script from there, what else should be altered?
Asked differently: What about the denoising strength and the original seed? Should they be the same or random/something else?

And a request: :D
Is it possible to add upscaling to the script? I have many 512px images, that I don't quite like, but would like your script used on AND simultaneously make it bigger to have it in one go. Would that be possible?

Edit:
And what about the prompt/negative prompt text? Should it be the same/empty/something else?

**Comment by Kahsolt** [comment]
Remember that sonar is just a simple k-diffusion sampler (wrapper) with several special tunable parameters. 
So it only overrides the `sampler method`, any other settings are all inherited from the main panel, the prompts, denoising strength, seed... just use it like a variation of `Euler` or `Euler a` sampler~

The upscaling is easy to add, I will make it possible.

**Comment by Kahsolt** [comment]
Though the momentum mechanism is a general idea and could be applied to any k-diffusion samplers, I only implemented it on `Euler` and `Euler a` because their code are simple, while other k-diffusion based samplers have already been developed to a messy  stuff by various tricky technics... 🤣

**Comment by Woisek** [comment]
> Remember that sonar is just a simple k-diffusion sampler (wrapper) with several special tunable parameters. So it only overrides the `sampler method`, any other settings are all inherited from the main panel, the prompts, denoising strength, seed... just use it like a variation of `Euler` or `Euler a` sampler~

OK, then I got it right. Thanks!

> The upscaling is easy to add, I will make it possible.

Yeah, great news! many thanks. And thanks for your great work you do for us!

**Comment by Woisek** [comment]
Many thanks for the upscale option. Works perfect!

**Comment by ruSauron** [comment]
How do I start using it?
I looked through the list of tabs, txt2img, img2img and I can't find anything with the word sonar.

**Comment by Woisek** [comment]
> How do I start using it? I looked through the list of tabs, txt2img, img2img and I can't find anything with the word sonar.

**Comment by Woisek** [comment]
He's right. The Sonar extension seems to be missing in the scripts dropdown ... :/

**Comment by ruSauron** [comment]
> How do I start using it? I looked through the list of tabs, txt2img, img2img and I can't find anything with the word sonar.

Fixed now, check Scripts tab
